### ISSUE TITLE
you can use commits, too

### ISSUE THREAD

**Issue by ahmetalpbalkan** [hodgesmr/FindGitHubEmail#11]
If you add `.patch` to someone's commit URL, you can get their email.

For instance your script didn't work for https://github.com/dhillii but I found their email manually by applying this trick.

**Comment by glennblock** [comment]
@ahmetalpbalkan can you give an example of a commit url that returns an email?

**Comment by glennblock** [comment]
You can get it off of the sha of any commit i.e. https://api.github.com/repos/glennblock/scriptcs/commits/042415f86b6b063d595269014475de4a48e1afde will show mine.

**Comment by ahmetalpbalkan** [comment]
Here is the email for that commit: https://github.com/glennblock/scriptcs/commit/042415f86b6b063d595269014475de4a48e1afde.patch 😉

**Comment by glennblock** [comment]
Aah I see, if you use the API you get JSON and can easily parse it out. This worked great for me though, thanks!

**Comment by ahmetalpbalkan** [comment]
@glennblock you're right, apparently for a merge commit, .patch shows the commiter's email (as it is a diff output) but apparently the right commit ID returns committers' email on the API as well.

Cheers.

**Comment by glennblock** [comment]
Thank you. Had I not found your original comment I would babe probably given up :-)
